// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0IMxNe34UVu1F5exlXZump-82QqLaCZ0',
    appId: '1:994468511463:web:cc0fd36230c47e53a1ac42',
    messagingSenderId: '994468511463',
    projectId: 'setting-app-e30b8',
    authDomain: 'setting-app-e30b8.firebaseapp.com',
    storageBucket: 'setting-app-e30b8.appspot.com',
    measurementId: 'G-ZJ7YJPHSQ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9kscTDSCbQKfnrp4D-N_iilorapLay5o',
    appId: '1:994468511463:android:6a3ce3ca3300883ea1ac42',
    messagingSenderId: '994468511463',
    projectId: 'setting-app-e30b8',
    storageBucket: 'setting-app-e30b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvlGs3rsfx1oZ1k6jhdlQOi-Gz403HWSo',
    appId: '1:994468511463:ios:0a0fd7e0d79864eda1ac42',
    messagingSenderId: '994468511463',
    projectId: 'setting-app-e30b8',
    storageBucket: 'setting-app-e30b8.appspot.com',
    iosBundleId: 'com.example.blocSettings',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvlGs3rsfx1oZ1k6jhdlQOi-Gz403HWSo',
    appId: '1:994468511463:ios:0a0fd7e0d79864eda1ac42',
    messagingSenderId: '994468511463',
    projectId: 'setting-app-e30b8',
    storageBucket: 'setting-app-e30b8.appspot.com',
    iosBundleId: 'com.example.blocSettings',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0IMxNe34UVu1F5exlXZump-82QqLaCZ0',
    appId: '1:994468511463:web:9809dfc70b00ee2fa1ac42',
    messagingSenderId: '994468511463',
    projectId: 'setting-app-e30b8',
    authDomain: 'setting-app-e30b8.firebaseapp.com',
    storageBucket: 'setting-app-e30b8.appspot.com',
    measurementId: 'G-W037ZF5TW6',
  );

}